# Generated by Django 3.2.20 on 2023-09-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_articles_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
