# Generated by Django 3.2.20 on 2023-09-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rohit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vgdhf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bvvnf', models.BigIntegerField()),
                ('tryrui', models.BigIntegerField()),
            ],
        ),
    ]
