# Generated by Django 3.2.20 on 2023-09-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_vgdhf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cvbcnfjfjfjgjhgj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bcbvfjfbvnfjfjfjjfkfmkvmvmbncnfkdkfkkffkfkkfkgfbxfzdfggrtjtjcucrtuctjcrththcrtrhxtrhx', models.BigIntegerField()),
            ],
        ),
    ]
